package com.barbasdev.weatherappsample.di

object RepositoryConstants {
    const val REPOSITORY_MEMORY_APIXU           = "REPOSITORY_MEMORY_APIXU"
    const val REPOSITORY_MEMORY_OPENWEATHER     = "REPOSITORY_MEMORY_OPENWEATHER"
    const val REPOSITORY_ROOM_APIXU             = "REPOSITORY_ROOM_APIXU"
    const val REPOSITORY_ROOM_OPENWEATHER       = "REPOSITORY_ROOM_OPENWEATHER"
    const val REPOSITORY_REALM_APIXU            = "REPOSITORY_REALM_APIXU"
    const val REPOSITORY_REALM_OPENWEATHER      = "REPOSITORY_REALM_OPENWEATHER"
}